import 'package:flutter/material.dart';

/// An enum to define the type of drawing primitive.
enum PocDrawingType { path, polygon }

/// A class representing a single drawing command for our custom renderer.
class PocDrawCommand {
  const PocDrawCommand({
    required this.type,
    required this.styleId,
    required this.points,
    this.strokeWidth,
  });

  /// The unique ID that maps to a specific style (e.g., color, fill).
  final int styleId;

  /// The type of primitive to draw.
  final PocDrawingType type;

  /// The geometric points for the shape, scaled to a 256x256 tile size.
  final List<Offset> points;

  /// The stroke width, which is often consistent across themes.
  final double? strokeWidth;
}

/// A static class to hold our fake tile data for the proof of concept.
class PocTileData {
  // Style IDs. In a real implementation, these would be generated by the
  // offline tool by analyzing the theme files.
  static const int greenSpaceStyleId = 1;
  static const int waterStyleId = 2;
  static const int houseStyleId = 3;
  static const int primaryRoadStyleId = 4;
  static const int secondaryRoadStyleId = 5;

  /// A static list of drawing commands representing one pre-processed tile.
  /// The renderer will simply iterate through this list and draw.
  static final List<PocDrawCommand> commands = [
    // Background elements are drawn first.
    const PocDrawCommand(
      type: PocDrawingType.polygon,
      styleId: greenSpaceStyleId,
      points: [Offset(0, 0), Offset(256, 0), Offset(256, 256), Offset(0, 256)],
    ),
    const PocDrawCommand(
      type: PocDrawingType.polygon,
      styleId: waterStyleId,
      points: [
        Offset(0, 180),
        Offset(150, 220),
        Offset(130, 256),
        Offset(0, 256)
      ],
    ),

    // Roads
    const PocDrawCommand(
      type: PocDrawingType.path,
      styleId: primaryRoadStyleId,
      strokeWidth: 8.0,
      points: [
        Offset(50, 0),
        Offset(60, 150),
        Offset(200, 200),
        Offset(256, 190)
      ],
    ),
    const PocDrawCommand(
      type: PocDrawingType.path,
      styleId: secondaryRoadStyleId,
      strokeWidth: 4.0,
      points: [Offset(0, 80), Offset(150, 90), Offset(200, 140)],
    ),

    // Foreground elements (houses) drawn on top.
    const PocDrawCommand(
      type: PocDrawingType.polygon,
      styleId: houseStyleId,
      points: [Offset(70, 20), Offset(90, 20), Offset(90, 40), Offset(70, 40)],
    ),
    const PocDrawCommand(
      type: PocDrawingType.polygon,
      styleId: houseStyleId,
      points: [
        Offset(100, 50),
        Offset(120, 50),
        Offset(120, 70),
        Offset(100, 70)
      ],
    ),
    const PocDrawCommand(
      type: PocDrawingType.polygon,
      styleId: houseStyleId,
      points: [
        Offset(20, 100),
        Offset(40, 100),
        Offset(40, 120),
        Offset(20, 120)
      ],
    ),
  ];
}
